import { CardObject } from "../App";

export const dummyCardObjects: CardObject[] = [
  {
    id: 1,
    title: "First Card",
    description: "first card",
    status: "todo",
    type: "task",
  },
  {
    id: 2,
    title: "Second Card",
    description: "second card",
    status: "todo",
    type: "bug",
  },
  {
    id: 3,
    title: "Third Card",
    description: "third card",
    status: "in-progress",
    type: "bug",
  },
  {
    id: 4,
    title: "Fourth Card",
    description: "ABCDE",
    status: "done",
    type: "feature",
  },
  {
    id: 5,
    title: "Fifth Card",
    description: "FGHIJ",
    status: "done",
    type: "feature",
  },
  {
    id: 6,
    title: "Sixth Card",
    description: "KLMNO",
    status: "done",
    type: "feature",
    assignedTo: "John Doe",
  },
  {
    id: 7,
    title: "Seventh Card",
    description: "PQRST",
    status: "done",
    type: "feature",
  },
  {
    id: 8,
    title: "Eighth Card",
    description: "UVWXY",
    status: "done",
    type: "bug",
    assignedTo: "John Doe",
  },
  {
    id: 9,
    title: "Ninth Card",
    description: "Z",
    status: "done",
    type: "bug",
    assignedTo: "Someone Else",
  },
  {
    id: 10,
    title: "Tenth Card",
    description: "tenth card",
    status: "done",
    type: "task",
    assignedTo: "Someone Else",
  },
  {
    id: 11,
    title: "Eleventh Card",
    description: "eleventh card",
    status: "done",
    type: "task",
    assignedTo: "Another Person",
  },
  {
    id: 12,
    title: "Twelfth Card",
    description: "twelfth card",
    status: "in-progress",
    type: "task",
    assignedTo: "Another Person",
  },
  {
    id: 13,
    title: "Thirteenth Card",
    description: "thirteenth card",
    status: "todo",
    type: "bug",
  },
  {
    id: 14,
    title: "Fourteenth Card",
    description: "fourteenth card",
    status: "feature",
    type: "bug",
  },
  {
    id: 15,
    title: "Fifteenth Card",
    description: "fifteenth card",
    status: "done",
    type: "bug",
  },
];
